name: tienda
description: Tienda online

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: any
  flutter_launcher_icons: ^0.7.4
  scrollable_positioned_list: ^0.1.7
  carousel_slider: ^2.2.1
  font_awesome_flutter: ^8.8.1
  shared_preferences: ^2.0.6
  modal_bottom_sheet: ^2.0.0
  http: ^0.13.1
  ftoast: ^1.0.0
  provider: ^4.3.3

  #flutter_zoom_drawer: ^2.0.2+4
  direct_select: ^2.0.0

  flutter_localizations:
    sdk: flutter
  #easy_localization: ^2.0.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/img/
    - assets/img/productos/
    - assets/img/logo/

flutter_icons:
  ios: true
  android: true
  image_path: "assets/img/logo/APiconoapp.png"
